window:
  padding:
    x: 5
    y: 5

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Iosevka Term
    style: Regular
  bold:
    family: Iosevka Term
    style: Bold
  italic:
    family: Iosevka Term
    style: Italic
  bold_italic:
    family: Iosevka Term
    style: Bold Italic

  size: 16.0

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: "0x1a1b26"
    foreground: "0xc0caf5"

  normal:
    black: "0x15161e"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: Off

shell:
  program: /bin/fish

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
