# ── Theme ─────────────────────────────────────────────────────────────────────
theme = "tomorrow_night_blue"

# ── Editor Settings ───────────────────────────────────────────────────────────
[editor]
auto-format = true
mouse = true
bufferline = "always"
cursorline = true
color-modes = true
auto-info = true
line-number = "relative"
true-color = true
trim-trailing-whitespace = true
continue-comments = true
completion-trigger-len = 1
completion-timeout = 5

# Cursor shapes
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# File picker
[editor.file-picker]
hidden = false

# Indent guides
[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "▢"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

# LSP integration
[editor.lsp]
display-messages = true
display-inlay-hints = false
auto-signature-help = true
snippets = true
goto-reference-include-declaration = false

# Statusline
[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"

# Gutters
[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
# ── Keybindings ───────────────────────────────────────────────────────────────

[keys.normal]
C-s = ":write"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-s = ":write"
